version: 0.1
    phases:
    build:
    commands:
    - npm install
    - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template sam.deploy

    artifacts:
    type: zip
    files:
    - sam.deploy
