AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: VegeChat is the skill to answer vegetable information

Resources:
  VegeChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VegeChatFunction
      CodeUri: s3://alexa-skill-horsewin/vegechat.zip
      Description: A function for VegeChat Alexa Skill
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 7
      Role:

      Events:
        AlexaSkillEvent:
          Type: AlexaSkill